accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns=[
    path('before_signup/', views.ManagerStatusView.as_view(), name='before_signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/<int:is_manager>', views.SignUpView.as_view(), name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from shifts.api_urls import router as api_router

#from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shifts/', include('shifts.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include(api_router.urls)),
]

shifts/urls.py
from django.urls import path
from shifts.views import mobileapp


app_name = 'shifts'

urlpatterns=[
    path('index/', mobileapp.HomeView.as_view(), name='index'),
    path('index/<int:year>/<int:month>/<int:day>/', mobileapp.HomeView.as_view(), name='index'),
    path('index/shiftsadd/', mobileapp.ShiftAddView.as_view(), name='shiftsadd'),
    path('availability/', mobileapp.AvailabilityHomeView.as_view(), name='availability'),
    path('availability/<int:year>/<int:month>/', mobileapp.AvailabilityHomeView.as_view(), name='availability'),
    path('availability/<int:year>/<int:month>/<int:day>/', mobileapp.AvailabilityHomeView.as_view(), name='availability'),
    path('availability/add/', mobileapp.AvailabilityAddView.as_view(), name='availabilityadd'),
    path('availability/add/<int:month>/<int:day>/', mobileapp.AvailabilityAddView.as_view(), name='availabilityadd'),
    path('assign/', mobileapp.ShiftsAssignView.as_view(), name='assign'),
    path('assign/<int:schedule_id>/', mobileapp.ShiftsAssignView.as_view(), name='assign'),
]

shifts/models.py
from django.db import models
import datetime
from django.utils import timezone
from accounts.models import UserManager

class Schedule(models.Model):
    class Meta:
        db_table = 'schedule'
    user = models.ForeignKey(UserManager, on_delete=models.PROTECT)
    schedule_id = models.AutoField(primary_key=True, unique=True)
    start_time = models.TimeField('start time', default=datetime.time(7,0,0))
    end_time = models.TimeField('end time', default=datetime.time(7,0,0))
    date = models.DateField('date', default=timezone.now)
    created_at = models.DateField('date modified', default=timezone.now)

    def __str__(self):
        return self.date


class Availability(models.Model):
    class Meta:
        db_table = 'availability'
    user = models.ForeignKey(UserManager, on_delete=models.PROTECT)
    available = models.CharField('available', default=1, max_length=30)
    start_time = models.TimeField('start time', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('end time', default=datetime.time(7, 0, 0))
    date = models.DateField('date', default=timezone.now)
    created_at = models.DateField('date modified', default=timezone.now)

    def __str__(self):
        return self.available


class Shifts(models.Model):
    class Meta:
        db_table = 'shifts'
    schedule = models.ForeignKey(Schedule, on_delete=models.PROTECT)
    assigned_user = models.CharField('assgined_user', default="", max_length=30)
    created_at = models.DateField('date modified', default=timezone.now)

    def __str__(self):
        return self.assigned_user

shifts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import View
import calendar
from collections import deque
from shifts.models import Schedule, Availability
from django.views.generic import ListView, FormView, DeleteView
from django.contrib import messages
from .forms import ShiftAddForm, AvailabilityAddForm
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from datetime import datetime
from django.views import generic
import datetime
from django.shortcuts import render, redirect, reverse


class BaseCalendarMixin:
    """Base class for all calendar"""
    #0:starting on Monday, 1: starting on Tuesday, 6: starting on Sunday
    first_weekday = 0
    week_names = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

    def setup(self):
        """Setup calendar
        create instance for calendar.Calendar class
        """
        self._calendar = calendar.Calendar(self.first_weekday)

    def get_week_names(self):
        """changeable the first day for a week"""
        week_names = deque(self.week_names)
        week_names.rotate(-self.first_weekday)
        return week_names

class MonthCalendarMixin(BaseCalendarMixin):
    """Base class for monthly calendar"""

    @staticmethod
    def get_previous_month(date):
        """return previous month"""
        if date.month == 1:
            return date.replace(year=date.year-1, month=12, day=1)
        else:
            return date.replace(month=date.month-1, day=1)

    @staticmethod
    def get_next_month(date):
        """return next month"""
        if date.month == 12:
            return date.replace(year=date.year+1, month=1, day=1)
        else:
            return date.replace(month=date.month+1, day=1)

    def get_month_days(self, date):
        """return all days in the month"""
        return self._calendar.monthdatescalendar(date.year, date.month)

    def get_current_month(self):
        """return current month"""
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        if month and year:
            month = datetime.date(year=int(year), month=int(month), day=1)
        else:
            month = datetime.date.today().replace(day=1)
        return month

    def get_month_calendar(self):
        """return monthly calendar dictionary"""
        self.setup()
        current_month = self.get_current_month()
        calendar_data = {
            'now': datetime.date.today(),
            'days': self.get_month_days(current_month),
            'current': current_month,
            'previous': self.get_previous_month(current_month),
            'next': self.get_next_month(current_month),
            'week_names': self.get_week_names(),
        }
        return calendar_data


class WeekCalendarMixin(BaseCalendarMixin):
    """Base class for week calendar"""
    def get_week_days(self):
        #return all days in a week
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today().replace(day=1)
        #pickup the week
        for week in self._calendar.monthdatescalendar(date.year, date.month):
            #if date is founded, return the week
            if date in week:
                return week

    def get_week_calendar(self):
        """returns week calendar library"""
        self.setup()
        days = self.get_week_days()
        first = days[0]
        last = days[-1]
        calendar_data = {
            'now': datetime.date.today(),
            'days': days,
            'previous':first - datetime.timedelta(days=7),
            'next': first + datetime.timedelta(days=7),
            'week_names': self.get_week_names(),
            'first': first,
            'last': last,
        }
        return calendar_data

class WeekWithScheduleMixin(WeekCalendarMixin):
    """Edit shift in the week calendar"""
    model = Schedule
    date_field = 'date'
    order_field = 'start_time'

    def get_week_schedules(self, days):
        for day in days:
            lookup = {self.date_field: day}
            queryset = Schedule.objects.filter(**lookup)
            if self.order_field:
                queryset = queryset.order_by(self.order_field)
            yield queryset

    def get_week_calendar(self):
        calendar_data = super().get_week_calendar()
        schedules = self.get_week_schedules(calendar_data['days'])
        calendar_data['schedule_list'] = schedules
        return calendar_data

class WeekWithAvailabilityMixin(WeekCalendarMixin):
    model = Availability
    date_field = 'date'
    order_field = 'start_time'

    def get_week_availability(self, days):
        for day in days:
            lookup = {self.date_field: day}
            queryset = Availability.objects.filter(**lookup)
            if self.order_field:
                queryset = queryset.order_by(self.order_field)
            yield queryset

    def get_week_calendar(self):
        calendar_data = super().get_week_calendar()
        availabilities = self.get_week_availability(calendar_data['days'])
        calendar_data['availability_list'] = availabilities
        return calendar_data


class HomeView(WeekWithScheduleMixin, generic.TemplateView):
    #template_name = 'shifts/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['week'] = self.get_week_calendar()
        context['user'] = self.request.user
        now = datetime.datetime.today()
        kwargs['month'] = now.month
        kwargs['year'] = now.year
        kwargs['day'] = now.day
        return context, redirect('shifts:index', kwargs)


class ShiftAddView(FormView):
    form_class = ShiftAddForm
    template_name = 'shifts/shiftsadd.html'
    success_url = reverse_lazy('shifts:index')

    def get_form_kwargs(self):
        #kwargs=dictionary
        kwargs = super(ShiftAddView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def post(self, request, *args, **kwargs):
        form = ShiftAddForm(request.POST, user=request.user)
        if not form.is_valid():
            return render(request, 'shifts/shiftsadd.html', {'form': form})
        form.save(commit=True)
        messages.success(request, "change has been saved")
        return redirect('shifts:index')

# class ShiftDeleteView(DeleteView):
#     model = Schedule
#     success_url = reverse_lazy('shifts:index')
#
#     def get(self, request, *args, **kwargs):
#         return self.post(request, *args, **kwargs)

class AvailabilityHomeView(MonthCalendarMixin, WeekWithAvailabilityMixin, generic.TemplateView):
    """home view for availability input"""
    template_name = 'shifts/availability.html'
    success_url = reverse_lazy('shifts:availability')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week = self.get_week_calendar()
        context['week'] = week
        context['month'] = self.get_month_calendar()
        context['week_row'] = zip(
            week['week_names'],
            week['days'],
            week['availability_list']
        )
        context['user'] = self.request.user
        return context


class AvailabilityAddView(FormView):
    form_class = AvailabilityAddForm
    template_name = 'shifts/availabilityadd.html'
    success_url = reverse_lazy('shifts:availability')

    def get_form_kwargs(self):
        kwargs = super(AvailabilityAddView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def post(self, request, *args, **kwargs):
        form = AvailabilityAddForm(request.POST, user=request.user)
        if not form.is_valid():
            return render(request, 'shifts/availabilityadd.html', {'form': form})
        availability_save = form.save(commit=False)
        availability_save.save()
        return redirect('shifts:availability')

shifts/views/calendar.py
import calendar
from collections import deque
from shifts.models import Schedule, Availability
from datetime import datetime
import datetime


class BaseCalendarMixin:
    """Base class for all calendar"""
    #0:starting on Monday, 1: starting on Tuesday, 6: starting on Sunday
    first_weekday = 0
    week_names = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

    def setup(self):
        """Setup calendar
        create instance for calendar.Calendar class
        """
        self._calendar = calendar.Calendar(self.first_weekday)

    def get_week_names(self):
        """changeable the first day for a week"""
        week_names = deque(self.week_names)
        week_names.rotate(-self.first_weekday)
        return week_names


class MonthCalendarMixin(BaseCalendarMixin):
    """Base class for monthly calendar"""

    @staticmethod
    def get_previous_month(date):
        """return previous month"""
        if date.month == 1:
            return date.replace(year=date.year-1, month=12, day=1)
        else:
            return date.replace(month=date.month-1, day=1)

    @staticmethod
    def get_next_month(date):
        """return next month"""
        if date.month == 12:
            return date.replace(year=date.year+1, month=1, day=1)
        else:
            return date.replace(month=date.month+1, day=1)

    def get_month_days(self, date):
        """return all days in the month"""
        return self._calendar.monthdatescalendar(date.year, date.month)

    def get_current_month(self):
        """return current month"""
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        if month and year:
            month = datetime.date(year=int(year), month=int(month), day=1)
        else:
            month = datetime.date.today().replace(day=1)
        return month

    def get_month_calendar(self):
        """return monthly calendar dictionary"""
        self.setup()
        current_month = self.get_current_month()
        calendar_data = {
            'now': datetime.date.today(),
            'days': self.get_month_days(current_month),
            'current': current_month,
            'previous': self.get_previous_month(current_month),
            'next': self.get_next_month(current_month),
            'week_names': self.get_week_names(),
        }
        return calendar_data


class WeekCalendarMixin(BaseCalendarMixin):
    """Base class for week calendar"""
    def get_week_days(self):
        #return all days in a week
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today().replace(day=1)
        #pickup the week
        for week in self._calendar.monthdatescalendar(date.year, date.month):
            #if date is founded, return the week
            if date in week:
                return week

    def get_week_calendar(self):
        """returns week calendar library"""
        self.setup()
        days = self.get_week_days()
        first = days[0]
        last = days[-1]
        calendar_data = {
            'now': datetime.date.today(),
            'days': days,
            'previous': first - datetime.timedelta(days=7),
            'next': first + datetime.timedelta(days=7),
            'week_names': self.get_week_names(),
            'first': first,
            'last': last,
        }
        return calendar_data


class WeekWithScheduleMixin(WeekCalendarMixin):
    """Edit shift in the week calendar"""
    date_field = 'date'
    order_field = 'start_time'

    def get_week_schedules(self, days):
        for day in days:
            lookup = {self.date_field: day}
            queryset = Schedule.objects.filter(**lookup)
            if self.order_field:
                queryset = queryset.order_by(self.order_field)
            yield queryset

    def get_week_calendar(self):
        calendar_data = super().get_week_calendar()
        schedules = self.get_week_schedules(calendar_data['days'])
        calendar_data['schedule_list'] = schedules
        return calendar_data


class WeekWithAvailabilityMixin(WeekCalendarMixin):
    model = Availability
    date_field = 'date'
    order_field = 'start_time'

    def get_week_availability(self, days):
        for day in days:
            lookup = {self.date_field: day}
            queryset = Availability.objects.filter(**lookup)
            if self.order_field:
                queryset = queryset.order_by(self.order_field)
            yield queryset

    def get_week_calendar(self):
        calendar_data = super().get_week_calendar()
        availabilities = self.get_week_availability(calendar_data['days'])
        calendar_data['availability_list'] = availabilities
        return calendar_data

shifts/templates/shifts/availability.html
{% block content %}
<style>
    table {
        table-layout: fixed;
    }

    td > div {
      height: 100px;
      overflow: hidden;
      white-space: nowrap;
    }
</style>
<br>
<a href="{% url 'shifts:availability' year=month.previous.year month=month.previous.month %}">Last Month</a>
{{ month.current | date:"Y/m" }}
<a href="{% url 'shifts:availability' year=month.next.year month=month.next.month %}">Next Month</a>

<br>
<table class="table">
    <thead>
       <tr>
      {% for w in month.week_names %}
        <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for week in month.days %}
      <tr>
        {% for day in week %}
          {% if month.now == day %}
            <td class="table-success">
          {% else %}
            <td>
          {% endif %}
          {% if month.current.month != day.month %}
             <a href="{% url 'shifts:availability' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
          {% else %}
          <a href="{% url 'shifts:availability' day.year day.month day.day %}">{{ day.day }}</a>
          {% endif %}
          </td>
        {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>
<br><br>
<table class="table table-bordered">
    <tbody>
        {% for week_name, day, day_schedule_list in week_row %}
            <tr>
                <td>
                    {% if week.first.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}
                    ({{ week_name }})
                </td>
                <td>
                    {% for a in day_availability_list %}
                        {{ a.start_time }} - {{ a.end_time }} <br>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
 <a href="{% url 'shifts:availabilityadd' %}">add</a>
{% endblock %}

shifts/templates/shifts/availabilityadd.html
{% block content %}

<body>
    <form method="post">
        {% csrf_token %}
        <div>
            <h5>Add Availability</h5>
            <button type="button">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div>
            {{ form.as_p }}
        </div>
        <div>
            <input type="button" value="Close" onClick="location.href='{% url 'shifts:availability' %}'">
            <button type="submit">ADD </button>
        </div>
    </form>
</body>

{% endblock %}

shifts/templates/shifts/index.html
{% block content %}
<a href="{% url 'accounts:login' %}">Logout</a>
<br>
<br>
<a href="{% url 'shifts:availability' %}">Availability</a>
<br>
<br>
<a href="{% url 'shifts:index' week.previous.year week.previous.month week.previous.day %}">Last Week</a>
{{ week.first | date:"Y/m/d" }} ~ {{ week.last | date:"Y/m/d" }}
<a href="{% url 'shifts:index' week.next.year week.next.month week.next.day %}">Next Week</a>

<table border="1" width="800" cellpadding="10">
    <thead>
        <tr>
            <th></th>
            {% for w in week.week_names %}
            <th>{{ w }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            {% for day in week.days %}
                {% if week.now == day %}
                <td class="table-success">
                {% else %}
                <td>
                {% endif %}
            {% if week.first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        <tr>
            <td>shifts</td>
            {% for day_schedule_list in week.schedule_list %}
            <td>
                {% for s in day_schedule_list %}
                {{ s.start_time }} - {{ s.end_time }}
                <a href="{% url 'shifts:assign' s.schedule_id %}">Add</a><br>
                {% endfor %}
            </td>
            {% endfor %}

        </tr>
        {% for users in username %}
            <tr>
                <td>{{ users }}</td>
                    {% for day_availability_list in week.availability_list %}
                        {% for s in day_availability_list %}
                            {% if s.user == users %}
                            <td>{{ s.start_time }} - {{ s.end_time }}<br></td>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
<br>
<a href="{% url 'shifts:shiftsadd' %}">Shift Add</a>
{% endblock %}

shifts/templates/shifts/shiftsAssign.html
{% block content %}

<body>
    <form method="post">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
        </div>
        <div>
            <input type="button" value="Close" onClick="location.href='{% url 'shifts:index' %}'">
            <button type="submit">ADD </button>
        </div>
    </form>
</body>

{% endblock %}

shifts/templates/shifts/shiftsadd.html
{% block content %}

<body>
    <form method="post" action="{% url 'shifts:shiftsadd' %}">
        {% csrf_token %}
        <div>
            <h5>Add Shifts</h5>
            <button type="button">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div>
            {{ form.as_p }}
        </div>
        <div>
            <input type="button" value="Close" onClick="location.href='{% url 'shifts:index' %}'">
            <button type="submit">ADD <i class="fa fa-plus"></i></button>
        </div>
    </form>
</body>

{% endblock %}